name: CI

on:
  push:
    branches: [main]
    paths:
      - frontend/**
      - .github/workflows/**
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths:
      - frontend/**
defaults:
  run:
    working-directory: frontend
jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x]
    name: Build with ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: frontend/yarn.lock
      - run: npm ci
      - run: npm run build-prod

  test:
    strategy:
      matrix:
        node-version: [18.x]

    name: Run all tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: frontend/yarn.lock
      - run: npm ci

      - if: github.event_name == 'pull_request'
        name: Validate all commits from PR
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Linter
        run: npm run lint

      - name: Type checking
        run: npm run check-types

      - name: Run unit tests
        run: npm run test
